function f0() {
    throw new Test262Error();
}
var v0 = {
    *method({
        x: y = thrower()
    }) {
    }
};
v0[f0 == ''](RangeError, function eval() {
    var y = 42;
    assertFalse(v14, b, 20);
    'function';
});